version: '3.8'

services:
  # BillGets Service
  billgets:
    build: .
    container_name: billgets_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5001
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    restart: unless-stopped